### ISSUE TITLE
Allow to specify default language for external snippets

### ISSUE THREAD

**Issue by PissedCapslock** [luciad/typescript-documentation#25]
Currently the behavior is as follows:

> language is optional but must be one of the languages made available in .babelrc for highlighting to work. The supported languages are: 'javascript', 'json', 'css'.
>
> If no language is specified, none is assigned.

It would be more convenient if there was an extra option to specify the default language for code snippets.
When that option is specified:
- The specified language is selected when the external snippet does not specify a language
- External snippets which are regular text should specify `none` as language, and the tool should be smart enough to recognize this and don't try to apply syntax highlighting

**Comment by TijlB99** [comment]
I have added a feature where if no language is specified, it looks at the file extension to decide the language. Is this a viable alternative?

**Comment by PissedCapslock** [comment]
Not really for our case, because our snippet files don't have an extension.

**Comment by TijlB99** [comment]
It now is possible with `-l defaultLan` tag (eg. `-l javascript`).
