### ISSUE TITLE
The absolute links don't allow hosting the site into a subdirectory

### ISSUE THREAD

**Issue by PissedCapslock** [luciad/typescript-documentation#35]
Absolute links like for example used in src/components/center/main/main-page.js

```
<Link to="/overview">Go to module overview</Link>
```

don't work in the following scenario:

- Generate the static site
- Throw it a subdirectory of an existing website

E.g. when I put the static site into a webserver so that the index page is `http://localhost:8072/docs/public/index.html`, the link will point to `http://localhost:8072/overview` instead of `http://localhost:8072/docs/public/overview`

**Comment by TijlB99** [comment]
Solved: example use: `l-td -p /docs/public`
